name: FirstActions 

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
  
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: run a one-line script 
        run: echo Hello, world!
      - name: run a multi-line script 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
